### ISSUE TITLE
JWT duplicate token error

### ISSUE THREAD

**Issue by alexx855** [Web3Auth/web3auth-backend#14]
Hello, 

im getting this error when trying to connect on a nodejs backend using the examples here, i always get this duplicate token error  [https://web3auth.io/docs/troubleshooting/jwt-errors#duplicate-token](https://web3auth.io/docs/troubleshooting/jwt-errors#duplicate-token)

Should i refresh the token somehow? can't find anything about it in the docs or a method that does that. 

Im able to connect successfully in the front end client:

```javascript
const web3auth = new Web3AuthCore({
  clientId,
  chainConfig: {
    chainNamespace: CHAIN_NAMESPACES.EIP155,
    chainId: "0x7E4",
    rpcTarget: "https://api.roninchain.com/rpc",
    blockExplorer: "https://explorer.roninchain.com"
  },
  web3AuthNetwork: "testnet"
});

const openloginAdapter = new OpenloginAdapter({
  adapterSettings: {
    uxMode: "redirect",
    loginConfig: {
      jwt: {
        name: "",
        verifier: "",
        typeOfLogin: "jwt",
        clientId,
      },
    },
  },
});

web3auth.configureAdapter(openloginAdapter);

await web3auth.init();

const { idToken } = await web3auth.authenticateUser();
```

And im sending the idToken to a node.js server like in the examples of this repository:

```javascript
const provider = await web3auth.connect({
  verifier,
  verifierId,
  idToken,
});
```

Any help is really appreciated, thansk!

**Comment by chaitanyapotti** [comment]
you must never reuse a jwt token.
you should always use a new one.

**Comment by alexx855** [comment]
> you must never reuse a jwt token.
> you should always use a new one.

Hello @chaitanyapotti, thanks for your help.
I've tried that, i've created a new token just to auth on the nodejs backend and got the same error eve tought the token was never user before.

What method should i use to generate the jwt? maybe im doing it wrong, im using the open login adapter with firebase btw

**Comment by chaitanyapotti** [comment]
The token must be used within 1 min of being generated.
Pls share the exact error here

**Comment by alexx855** [comment]
Im getting the error:
 **Error: Duplicate token found**
im sending the token inmediatelly, so its not because of the 1 min limit, and im not using the token anywere else, im generating it like this: 
``` javascript
const { idToken } = await web3Auth.authenticateUser();```

i've created a repository to reproduce this here: https://github.com/alexx855/web3auth-backend

i can validate the token with the server /api/login but it fails with the error  **Error: Duplicate token found** when i try to login with the node sdk at /api/hello
