### ISSUE TITLE
Links in README point to permission denied xml

### ISSUE THREAD

**Issue by joewagner** [Web3Auth/web3auth-backend#18]
I've been learning about Web3Auth, and notice that the three links in the ["Choosing Between SDKs" section](https://github.com/Web3Auth/web3auth-backend/tree/main/packages/node-sdk#-choosing-between-sdks) of the README all return the following permission denied message.
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>EF27YKM1KBHC9VPY</RequestId>
<HostId>qdWJnLLmLkjEqKmpXQwy6UkBfmZ0eR883aZsvhZJpLLaaUiC+HIu5oDWFzPtragG8iF8OkpYPpFSJuvJmpFDlA==</HostId>
</Error>
```

**Comment by chaitanyapotti** [comment]
thanks for pointing out. it's fixed now
